name: student_model
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  provider: ^6.0.3
  hive_flutter: ^1.1.0
  image_picker: ^0.7.2+1
  path_provider: ^2.0.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - asset/
